# Generated by Django 4.2 on 2023-05-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('serviço', models.TextField(max_length=255)),
                ('valor', models.IntegerField()),
                ('cliente', models.TextField(max_length=255)),
                ('data', models.TextField(max_length=255)),
            ],
        ),
    ]
