# Generated by Django 4.2 on 2023-05-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0003_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='serviço',
            new_name='servico',
        ),
    ]
